# Generated by Django 2.1.4 on 2018-12-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181222_2213'),
        ('users', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
            ],
        ),
    ]
