# Generated by Django 2.1.4 on 2018-12-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_course_user'),
        ('users', '0007_remove_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
            preserve_default=False,
        ),
    ]
