# Generated by Django 2.1.4 on 2018-12-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
