# Generated by Django 2.1.4 on 2018-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20181226_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ManyToManyField(related_name='assignment_course_connect', to='users.Course'),
        ),
    ]
