# Generated by Django 2.1.4 on 2019-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20181226_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=1, max_length=1000000000),
            preserve_default=False,
        ),
    ]
