# Generated by Django 2.1.4 on 2019-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_assignment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.ManyToManyField(related_name='assignment_course_connect', to='users.Assignment'),
        ),
    ]
