# Generated by Django 2.1.4 on 2019-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190109_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ManyToManyField(related_name='assignment_course_connect', to='users.Course'),
        ),
    ]
