# Generated by Django 2.1.4 on 2019-01-10 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0032_auto_20190110_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ManyToManyField(related_name='assignment_user_connect', to=settings.AUTH_USER_MODEL),
        ),
    ]
