# Generated by Django 2.1.4 on 2019-01-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_assignment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
    ]
