# Generated by Django 2.1.4 on 2019-01-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190111_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeassignments',
            name='user',
        ),
    ]
