# Generated by Django 2.1.4 on 2019-01-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_gradeassignments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeassignments',
            name='course',
        ),
    ]
