# Generated by Django 2.1.4 on 2019-01-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_gradeassignments_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeassignments',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='GradeAssignments',
        ),
    ]
