# Generated by Django 2.1.4 on 2019-01-11 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0039_auto_20190111_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ManyToManyField(related_name='assignment_user_connect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeassignments',
            name='assignment',
            field=models.ManyToManyField(related_name='gradeassignment_assignment_connect', to='users.Assignment'),
        ),
        migrations.AddField(
            model_name='gradeassignments',
            name='course',
            field=models.ManyToManyField(related_name='gradeassignment_course_connect', to='users.Course'),
        ),
        migrations.AddField(
            model_name='gradeassignments',
            name='user',
            field=models.ManyToManyField(related_name='gradeassignment_user_connect', to=settings.AUTH_USER_MODEL),
        ),
    ]
