# Generated by Django 2.1.4 on 2019-01-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20190112_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
            preserve_default=False,
        ),
    ]
